### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by andymans** [nimblemachines/muforth#13]
Not an issue - just a thank you for such an excellent artefact!

I've recently been converted to Forth - it really is an excellent language - and have been looking for a decent implementation that will run nicely on the 64 bit mac. I'm really pleased with this!  Thanks Again!!

**Comment by nimblemachines** [comment]
Thanks for the nice comment!

Too bad muforth remains perpetually unfinished, undocumented, and experimental. ;-)

Just curious: What are you planning to use muforth for? You can email me privately if you like. My email address is in every commit message.

Also, there isn't good documentation on doing it, but adding new C primitives is very easy. If you want to know how to do this, and don't want to puzzle it out for yourself, just ask.
